### ISSUE TITLE
What do these addresses do？

### ISSUE THREAD

**Issue by w4454962** [ENAleksey/RenderEdge#10]
address_localDelay = address_GameBase + 0x660F01;
address_lanDelay = address_GameBase + 0x661A91;
address_netDelay = address_GameBase + 0x65DE41;

I tried to change the address value, but it didn't change in the game。

**Comment by ENAleksey** [comment]
Hi!

These addresses are used to set the delay values for issuing orders to units in milliseconds (for example, the time between pressing the right mouse button and the start of a unit's movement).

Default values:
- 100ms for local and lan game (I prefer 10ms)
- 250ms for net game

**Comment by w4454962** [comment]
If the game network delay is changed to 30ms and the player's current network delay is 50ms, will players be offline？

**Comment by ENAleksey** [comment]
I haven't tested this in multiplayer, so I can't say it won't happen for sure.

**Comment by w4454962** [comment]
I set a read breakpoint on localdelay, and there was no feedback, and the value modification had no effect in the game

**Comment by ENAleksey** [comment]
Which version of the Warcraft patch are you using?
Have you tried setting great value? For example 2000.

**Comment by w4454962** [comment]
Yes, I tried to modify it. The time didn't work. My local version of Warcraft is 1.26.0.6401

**Comment by w4454962** [comment]
Hey, long time no see. I retested these addresses and found that they are virtual functions of classes. They get fixed values before entering the game,

When I modify "address_lanDelay", I can extend the command receiving time, but shortening it has no effect,



The command packets of Warcraft will have a queue in the LAN. When the queue is not blocked, the receiving time will be triggered quickly. When the queue is blocked, a packet will be processed at a speed of 0.7s. There is no way to reduce the interval time.

In stand-alone games, packets are received directly after sending without queue, so do you know the principle and memory address of this part?

**Comment by ENAleksey** [comment]
Hi!
Sorry, I haven't worked with the netсode and don't know how to get rid of the queue or how to find these places in the warcraft code.

**Comment by w4454962** [comment]
ok thanks
